peercoin/peercoin

src/net.cpp
src/test/Checkpoints_tests.cpp
src/test/key_tests.cpp
src/test/test_bitcoin.cpp
src/test/transaction_tests.cpp
src/test/util_tests.cpp
src/util.cpp

Backported version of https://github.com/ppcoin/ppcoin/pull/110

Unit tests fixed

---

src/key.cpp

Proposal to fix the current fork between 32 and 64 bits systems.

Signature fix 2

---

bitcoin-qt.pro
src/bitcoinrpc.cpp
src/bitcoinrpc.h
src/kernelrecord.cpp
src/kernelrecord.h
src/main.h
src/makefile.linux-mingw
src/makefile.mingw
src/makefile.osx
src/makefile.unix
src/qt/bitcoingui.cpp
src/qt/bitcoingui.h
src/qt/guiconstants.h
src/qt/mintingfilterproxy.cpp
src/qt/mintingfilterproxy.h
src/qt/mintingtablemodel.cpp
src/qt/mintingtablemodel.h
src/qt/mintingview.cpp
src/qt/mintingview.h
src/qt/walletframe.cpp
src/qt/walletframe.h
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/qt/walletstack.cpp
src/qt/walletstack.h
src/qt/walletview.cpp
src/qt/walletview.h
src/rpcblockchain.cpp
src/rpcminting.cpp

I imported the minting tab from Peerunity.
I first rewrote the Peerunity master branch to keep only the minting tab related commits, and then merged that into the develop branch, which required significant adjustments (made inside the merge commit).
I tested it briefly and it seems to work like on Peerunity.

Minting tab

---

bitcoin-qt.pro
src/coincontrol.h
src/main.h
src/qt/bitcoingui.cpp
src/qt/coincontroldialog.cpp
src/qt/coincontroldialog.h
src/qt/coincontroltreewidget.cpp
src/qt/coincontroltreewidget.h
src/qt/forms/coincontroldialog.ui
src/qt/forms/optionsdialog.ui
src/qt/forms/sendcoinsdialog.ui
src/qt/optionsdialog.cpp
src/qt/optionsmodel.cpp
src/qt/optionsmodel.h
src/qt/sendcoinsdialog.cpp
src/qt/sendcoinsdialog.h
src/qt/sendcoinsentry.cpp
src/qt/sendcoinsentry.h
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/wallet.cpp
src/wallet.h

I imported Coin control from Nu 2.1 (because it already included peerunity and peercoin/develop), and then applied a few coin control related patches I could find.
I tested it on testnet and it seemed to work fine.

Coin control

---

README.md

Fixed some grammar in README.md

Fixed some grammar in README.md

---

src/bitcoinrpc.cpp
src/main.cpp
src/main.h
src/net.cpp
src/rpcrawtransaction.cpp
src/test/Gemfile.lock
src/test/containers/attach
src/test/containers/base/Dockerfile
src/test/containers/base_devel/Dockerfile
src/test/containers/build_net
src/test/containers/coin_container.rb
src/test/containers/node
src/test/features/revert_duplicate.feature
src/test/features/step_definitions/common.rb
src/test/features/step_definitions/revert_duplicate.rb

Rebase of sigmike's PR https://github.com/peercoin/peercoin/pull/165 on top of latest develop.
Removed the C++11 activation as it is not needed anymore since https://github.com/peercoin/peercoin/pull/169
Excluded the signature fixes as they were merged by https://github.com/peercoin/peercoin/pull/163

Duplicate best block (rebase from sigmike's PR)

---

contrib/vagrant/.gitignore
contrib/vagrant/Vagrantfile
contrib/vagrant/install.sh

Vagrant Build

---

src/main.cpp
src/qt/addressbookpage.cpp
src/qt/bitcoingui.cpp
src/qt/bitcoinstrings.cpp
src/qt/editaddressdialog.cpp
src/qt/forms/addressbookpage.ui
src/qt/forms/optionsdialog.ui
src/qt/forms/signverifymessagedialog.ui
src/qt/optionsdialog.cpp
src/qt/paymentserver.cpp
src/qt/res/bitcoin-qt.rc

Replaced mentions of bitcoin with peercoin.

Some more rebranding

---

COPYING

Update of COPYING

---

src/base58.h
src/bitcoinrpc.cpp
src/checkpoints.cpp
src/checkpoints.h
src/checkpointsync.cpp
src/checkpointsync.h
src/db.cpp
src/db.h
src/init.cpp
src/main.h
src/makefile.mingw
src/makefile.osx
src/makefile.unix
src/net.h
src/protocol.cpp
src/qt/bitcoin.cpp
src/qt/bitcoingui.cpp
src/rpcdump.cpp
src/rpcmining.cpp
src/rpcnet.cpp
src/rpcwallet.cpp
src/script.cpp
src/script.h
src/serialize.h
src/util.cpp
src/util.h
src/wallet.cpp
src/wallet.h
src/walletdb.cpp

Changed some copyright headers

Changed some copyright headers

---

INSTALL

Update of INSTALL

---

src/bitcoinrpc.cpp
src/qt/bitcoinstrings.cpp
src/qt/forms/optionsdialog.ui
src/qt/locale/bitcoin_en.ts
src/qt/optionsdialog.cpp
src/qt/optionsdialog.h
src/qt/optionsmodel.cpp
src/qt/optionsmodel.h
src/qt/sendcoinsdialog.cpp

:wave: @peerchemist @hrobeers @backpacker69 
This fella https://github.com/peercoin/peercoin/issues/198
I wrote a thing! Pulled back the changes to just remove text and option from the GUI options. Also ran the translation string extraction script and whatever `lupdate` is (some sort of QT tool?).
Can still send transactions on the testnet... so that's encouraging :rainbow:

[issue#198] No more GUI option for "additional transaction fee" :)

---

src/qt/bitcoinstrings.cpp

Corrected some changes in: https://github.com/peercoin/peercoin/pull/199

Corrected some changes in pull #199

---

doc/build-unix.md

Added build instructions for Debian based Linux to build-unix.md

Added build instructions for Debian based Linux

---

README.md

Some minor changes to README.md

Some minor changes to README.md

---

src/qt/clientmodel.cpp

fix minting warning

---

src/main.cpp

-nominting command line option

---

src/init.cpp

add -nominting to help

---

src/makefile.osx-mavericks

Changed one copyright header

---

.travis.yml

hallo peercoin people :leaves: :leaves: :leaves: @backpacker69 @hrobeers @peerchemist 
Here's a `.travis.yml` that could be used to automatically run peercoin tests (looks like https://travis-ci.org/belovachap/peercoin).

Messing around with Travis CI

---

doc/build-unix.md

Updated build notes for Linux

---

src/main.cpp

Prevent segfault when there's an invalid transaction in mempool

---

src/main.cpp
src/rpcmining.cpp

Should fix #233 "Crash on ConnectBlock failed"
I'm still testing this, so do not merge yet.

Fix Crash on ConnectBlock

---

src/rpcwallet.cpp

fixes https://github.com/peercoin/peercoin/issues/177

Add checkpoint status to getinfo

---

src/qt/guiconstants.h

fixes https://github.com/peercoin/peercoin/issues/224

Adapt minting tab colors from Peerunity

---

src/qt/transactionrecord.cpp
src/qt/transactiontablemodel.cpp

Fixes https://github.com/peercoin/peercoin/issues/223

Backport transactionrecord fixes from Peerunity

---

src/rpcwallet.cpp
src/wallet.cpp

backport from: https://github.com/bitcoin/bitcoin/pull/1850
should fix: https://github.com/peercoin/peercoin/issues/185

Fixes for when listtransactions encounters non-standard outputs

---

.gitignore
Makefile.am
src/Makefile.am
src/Makefile.qt.include
src/Makefile.qttest.include
src/Makefile.test.include

fixes https://github.com/peercoin/peercoin/issues/242

Replace all ppcoin names by peercoin in autotools makefiles

---

src/rpcwallet.cpp

@bananenwilly can you check if this fully fixes https://github.com/peercoin/peercoin/issues/185 for you?

Add stake information to coinstake inputs in listtransactions rpc

---

src/rpcclient.cpp

fix walletpassphrase parameter

---

src/checkpoints.cpp
src/kernel.cpp

Fix for issue: https://github.com/peercoin/peercoin/issues/253

Hardened checkpoint update for v0.6.2 at block 336000

---

src/rpcclient.cpp

i've compared all of the rpc parameters before autotools, so this should totally fix #248

fix rpc parameters after autotools merge

---

contrib/vagrant/Vagrantfile
contrib/vagrant/install.sh
contrib/vagrant/tor/install.sh

Updates for 061 vagrant ubuntu compile

Feature 061 vagrant compile

---

src/qt/locale/bitcoin_bg.ts
src/qt/locale/bitcoin_ru.ts

Peercoin: Пиркойн
Bitcoin: Биткоин

Replace Bitcoin with Peercoin in cyrillic

---

contrib/vagrant/install.sh

Compile using bdb48 script. Softlink include and lib.

softlink include and lib

---

.travis.yml
contrib/vagrant/install.sh

make check to run tests

---

.travis.yml
contrib/vagrant/Vagrantfile
contrib/vagrant/install.sh
scripts/docker/debian/Dockerfile-jessie
scripts/docker/debian/Dockerfile-stretch
scripts/install-ubuntu.sh
scripts/peercoinconf.sh

Build Debian in docker to verify build

Debian Docker builds

---

contrib/vagrant/Vagrantfile
contrib/vagrant/install.sh

#297
clean, move directory outside script

move directory outside script

---

.travis.yml
scripts/docker/debian/Dockerfile-jessie
scripts/docker/debian/Dockerfile-stretch
scripts/docker/windows-crosscompile/Dockerfile-xenial
scripts/windows-crosscompile/compile-libdb.sh
scripts/windows-crosscompile/compile-miniupnpc.sh
scripts/windows-crosscompile/compile-peercoin.sh
scripts/windows-crosscompile/dependencies.sh

Feature windows

---

doc/README.md
share/setup.nsi.in

Updated version number to 0.6.2

Updated version number to 0.6.2

---

src/bitcoin-cli.cpp

fix for peercoin-cli

---

contrib/debian/peercoin-qt.install
contrib/debian/peercoind.install
contrib/debian/peercoind.manpages

completing the debian package

---

contrib/debian/control
contrib/debian/rules

finishing touches to debian configuration

---

contrib/debian/rules

do full cleanup on dh_clean

---

build-aux/m4/ax_boost_base.m4

resolves problems on non x86_64 gnu-linux platforms

Boost lib detection problem fix

---

contrib/debian/rules

Fixes dangling quote
Parallel option

Feature debuild fix

---

.gitignore
.travis.yml
contrib/debian/rules
scripts/debuild.sh

Feature debuild

---

.travis.yml
scripts/travis-uninstall-packages.sh

Display travis build environment
Uninstall unnecessary packages for travis build

Feature travis env

---

bitcoin-qt.pro

Revert "add -pthread to LIBS for MXE win32 build in bitcoin-qt.pro, fix for v0.6.2ppc.rc4"

---

README.md

Added Peer4commit badge to README.md

Added Peer4commit badge to README.md

---

src/qt/bitcoingui.cpp

Some improvements for the GUI

---

src/net.cpp

Please contact TheSeven in case of any issues/outages.

Add mainnet DNS seed hosted by 7server.net

---

bitcoin-qt.pro
contrib/debian/manpages/peercoind.1
doc/README.md
doc/README_windows.txt
doc/build-unix.md
share/setup.nsi.in
src/clientversion.h

@peerchemist I have not bumped the Debian package version. You might want to do this.

Bump version to 0.6.4

---

src/checkpoints.cpp
src/kernel.cpp

Hardened checkpoint update for v0.6.4 at block 371850

Hardened checkpoint update for v0.6.4 at block 371850

---

contrib/gitian-docker/Dockerfile
contrib/gitian-docker/README.md
contrib/gitian-docker/build.sh
contrib/gitian-docker/setup.sh

some docker fixes to build peercoin

Dockerfixes

---

src/kernel.cpp

Extra hardened checkpoints added to kernel.cpp also.

extra hardened checkpoints added to kernel.cpp

---

src/checkpoints.cpp
src/kernel.cpp

Hardened checkpoint update for v0.7.0 testnet

Hardened checkpoint update for v0.7.0 testnet

---

src/qt/locale/bitcoin_en.ts

Weird spacing fix in bitcoin_en.ts also

Weird spacing fix in bitcoin_en.ts also

---

src/qt/locale/bitcoin_bg.ts
src/qt/locale/bitcoin_kk_KZ.ts
src/qt/locale/bitcoin_mk_MK.ts
src/qt/locale/bitcoin_sr.ts

Bitcoin to Peercoin in Cyrillic

Bitcoin to Peercoin in Cyrillic

---

src/qt/locale/bitcoin_bg.ts
src/qt/locale/bitcoin_bg_BG.ts
src/qt/locale/bitcoin_mk_MK.ts
src/qt/locale/bitcoin_mn.ts
src/qt/locale/bitcoin_ru_RU.ts
src/qt/locale/bitcoin_sr.ts

Some more Bitcoin to Peercoin in Cyrillic

Some more Bitcoin to Peercoin in Cyrillic

---

src/key.cpp
src/qt/forms/modaloverlay.ui
src/qt/forms/optionsdialog.ui
src/qt/forms/overviewpage.ui
src/qt/forms/receivecoinsdialog.ui
src/qt/forms/sendcoinsentry.ui
src/qt/forms/signverifymessagedialog.ui
src/qt/paymentserver.cpp

More rebranding

---

src/chainparams.cpp

Add dnsseed maintained at ppcoin.info.

Additional dnsseed

---

doc/README_windows.txt
src/checkpointsync.cpp
src/checkpointsync.h
src/kernel.cpp
src/kernel.h
src/kernelrecord.h
src/qt/mintingfilterproxy.h
src/qt/mintingtablemodel.h
src/qt/mintingview.cpp
src/qt/mintingview.h
src/qt/multisigaddressentry.h
src/qt/multisigdialog.h
src/qt/multisiginputentry.h
src/qt/res/bitcoin-qt-res.rc
src/test/pow_tests.cpp
src/univalue/test/unitester.cpp

MIT/X11 changed to MIT in some files

MIT/X11 changed to MIT in some files

---

README.md

Update links in README.md to work with new website

Update links in README.md to work with new website

---

src/chainparams.cpp
src/kernel.cpp

Hardened checkpoint update for v0.8.5 testnet and mainnet

Hardened checkpoint update for v0.8.5 testnet and mainnet

---

README.md

Change wiki link in README.md

---

doc/man/peercoin-qt.1
doc/man/peercoind.1

Fix correct start year for Peercoin

Fix correct start year for Peercoin

---

src/qt/walletview.cpp

fix unlock wallet issue

---

src/chainparams.cpp
src/kernel.cpp

Hardened checkpoint update for v0.9.0 testnet

Hardened checkpoint update for v0.9.0 testnet

---

src/chainparams.cpp
src/kernel.cpp

Hardened checkpoint update for v0.9.0 testnet 2

Hardened checkpoint update for v0.9.0 testnet 2

---

src/chainparams.cpp
src/kernel.cpp

Hardened checkpoint update for v0.9.0 testnet 3

Hardened checkpoint update for v0.9.0 testnet 3

---

src/chainparams.cpp
src/kernel.cpp

Hardened checkpoint update for v0.9.0 testnet 4

Hardened checkpoint update for v0.9.0 testnet 4

---

src/chainparams.cpp
src/kernel.cpp

Hardened checkpoint update for v0.10.0 mainnet

Hardened checkpoint update for v0.10.0 mainnet

---

README.md

Remove testing in README.md

---

src/qt/bitcoingui.cpp
src/qt/bitcoingui.h

Per https://github.com/peercoin/peercoin/issues/532

implement requested UX changes

---

.github/workflows/build.yml

Added build.yml for Sonarcloud

---

sonar-project.properties

sonar-project.properties

---

sonar-project.properties

Statically analyze that which you cannot possibly hope to manage as an individual.

fix java exclusion

---

src/qt/locale/bitcoin_ro.ts

Revert "Corrected romanian letters and errors"

---

src/chainparams.cpp
src/kernel.cpp

Hardened checkpoint update for v0.11.0 mainnet

Hardened checkpoint update for v0.11.0 mainnet

---

.github/workflows/build.yml

This commit will
- create a rolling release from develop branch
- categorize docker tags
- publish full releases on tag push
- sign off sha256sums of release
- add a torrent file of given release
Requires GPG_PRIVATE_KEY to be present.

automate releases

---

.github/workflows/build.yml

We only want to cache the result, not the downloaded sources.

Do not cache common downloads

---

src/qt/locale/bitcoin_en.ts
src/qt/locale/bitcoin_hr.ts
src/qt/locale/bitcoin_ru.ts

Remove some sync-checkpoint residue

Remove some sync-checkpoint residue

---

src/qt/locale/bitcoin_bg.ts
src/qt/locale/bitcoin_mn.ts
src/qt/locale/bitcoin_sr.ts

Changed Bitcoin to Peercoin in Cyrillic

Changed Bitcoin to Peercoin in Cyrillic

---

README.md

Add comma to README.md

---

.github/workflows/build.yml

Merge build.yml from develop

---

README.md

Revert changes to README.md

---

.github/workflows/build.yml

+ build: update appimage builder
+ build: fixed version for base images

build: update appimage builder

---

.github/workflows/build.yml

The appimage builder was trying to pull a non-existent / deprecated package from apt. This PR fixes that.

temp fix dpkg appimage install

---

src/qt/bitcoin.cpp
src/qt/bitcoin.h
src/qt/forms/intro.ui
src/qt/guiconstants.h
src/qt/intro.cpp
src/qt/intro.h
src/qt/optionsmodel.cpp
src/qt/optionsmodel.h

This PR removes pruning residues from Qt code, with the exception of localization files.

qt: Remove the rest of the pruning code

---

src/chainparams.cpp

Update nMinimumChainWork and defaultAssumeValid to block 650000 on mainnet

Update nMinimumChainWork and defaultAssumeValid

---

src/qt/locale/bitcoin_ja.ts
src/qt/locale/bitcoin_ja_JP.ts

ビットコイン→ピアコイン
Bitcoin→Peercoin
Inspired by that other tl PR.

Update japanese translation

---

src/qt/locale/bitcoin_ko.ts

Peercoin is 피어코인 in Korean

---

src/wallet/interfaces.cpp
src/wallet/scriptpubkeyman.cpp
src/wallet/wallet.cpp

allow spending from pubkeys

---

src/clientversion.cpp

Minor fix addressing the issue described in https://github.com/peercoin/peercoin/issues/695.

Set correct start year for Bitcoin

---

src/kernel.cpp
src/kernel/chainparams.cpp

Hardened checkpoint update for v0.13.0 testnet

Hardened checkpoint update for v0.13.0 testnet

---

src/wallet/wallet.cpp

fix coinstake size fee allowance

---

src/wallet/wallet.cpp

Release 0.14

---

src/kernel/chainparams.cpp

Update nMinimumChainWork and defaultAssumeValid to block 750000

Update nMinimumChainWork and defaultAssumeValid to block 750000

---

src/version.h

Disconnect from older peers

---

src/wallet/wallet.h

Set default for -combinecoins to true

Set default for -combinecoins to true

---

src/wallet/wallet.cpp

Set -maxmintingutxos in accordance with RFC28

Set -maxmintingutxos in accordance with RFC28

---

src/kernel.cpp
src/kernel/chainparams.cpp

Checkpoint update for v0.14.0 mainnet

Checkpoint update for v0.14.0 mainnet

---

.github/workflows/build.yml
contrib/guix/Dockerfile
contrib/guix/libexec/build.sh
contrib/guix/manifest.scm

This is a general update to the pipeline.
This commit gets rid of the extraneous 10-20min wait-time which was introduced on the switch to guix.
It also drops appimage support, since that appears to be a dead end upstream.

better guix caching

---

.github/workflows/build.yml
contrib/guix/Dockerfile

This makes depends build survive cross branch and tag.

cache depends via docker

---

src/kernel.cpp
src/node/miner.cpp

Release 0.15

---

.github/workflows/build.yml

Didn't think of this earlier, sorry.

allow binary job to run if guix build is skipped
