- src/kernel.cpp
- src/kernel.h
- src/main.cpp
On testnet, the BIP34 softfork get's accidently activated prematurely. Probably due to experimentation with the version number on testnet.
A protocol v0.6 switchtime should still be decided on.
Note that BIP34 is just a soft fork, legacy clients will still accept blocks created after activation.
> [ppcoin v0.6] Prevent premature activation of BIP34 softfork

- src/main.cpp
Handles the ThreadStakeMinter exception thrown at client shutdown:
```
************************
UNKNOWN EXCEPTION       
peercoin in ThreadStakeMinter() 
```
> Handle thread_interrupted exception in ThreadStakeMinter()

- src/wallet.cpp
Avoid confusion, we still did not remove the timestamp, so let's stick to it.
Fixes: https://github.com/peercoin/peercoin/issues/156
> CWalletTx::GetTxTime() should return the peercoin txtime

- src/init.cpp
- src/main.cpp
- src/main.h
Node memory can get exhausted because of too high mapOrphanTransactions limit and unlimited mapOrphanBlocks size.
Both limits are made configurable.
> Fix DoS vulnerability by flooding Orphan mempools

- src/base58.h
- src/bignum.h
- src/crypter.cpp
- src/key.cpp
- src/key.h
Runs and tests pass using openssl 1.1.0.f on Archlinux
Also tested for backwards compatibility with openssl 1.0
Please test if it compiles and runs on your system, heavy testing will be done on the second fork client.
> Fix OpenSSL v1.1 compatibility

- src/bignum.h
plz test if this fixes the issues building with old compilers
> nullptr -> NULL: removing the dependency on a c++11 complient compiler

- src/kernel.cpp
- src/main.cpp
The bool fValidatePayToScriptHash got replaced by script verification flags but the call still passed a boolean as the new flag parameter.
Bound checks missing from CScriptCheck triggers std::bad_alloc errors on coinstake validation on some invalid testnet blocks.
> Fix VerifySignature mistakes made with v0.6 port

- bitcoin-qt.pro
This should hopefully show v.0.6.0 in the information tab in the debug window.
> Show correct version number in debug window info

- src/qt/guiutil.cpp
- src/qt/guiutil.h
This is a fix for the missing rebranding reported by Willy here:
[https://talk.peercoin.net/t/v0-6-public-testing/6103/7](https://talk.peercoin.net/t/v0-6-public-testing/6103/7)
> Rebranding of debug window (show command-line options)

- src/qt/bitcoingui.cpp
- src/qt/res/themes/default.qss
Changed color of text in status bar from gray to white since it was a bit hard to see. Text is shown when you hover over the buttons in the tool bar. I have tested this and it works.
> Changed color of text in status bar

- src/qt/bitcoingui.cpp
Fix for no text is shown in status bar when you hover over the minting button with your mouse.
I have tested this and it works.
Ref: https://github.com/peercoin/peercoin/issues/182
> Fix for no text shown in status bar when hovering minting button

- .gitignore
- bitcoin-qt.pro
- src/makefile.mingw
These are the code changed i needed to make to build the Windows exes using MXE on Ubuntu Linux 14.04 and 16.04
I have an update to the peercoin-qt.exe using MXE wiki, but i wanted to get this patch accepted before making an update (see below for additional windows qrencode support). I also have notes on building peercoind.exe with MXE to submit for review. 
MXE does not provide the script for libqrencode, but there is a qrencode.mk pull request pending. https://github.com/mxe/mxe/pull/1890
To use, download to your local mxe/src/ directory. 
> cd src
> wget https://raw.githubusercontent.com/nohea/mxe/qrencode-add/src/qrencode.mk
> cd ..
Run `make qrencode` just like the supported packages:
> make qrencode
libqrencode will be built in your mxe installation, and you may pass the …
> updates for win build on linux via MXE: qt and daemon

- src/bitcoinrpc.cpp
- src/rpcblockchain.cpp
This patch moves the 2nd parameter [txinfo] to the 3rd paramter.
The 2nd parameter of getblock becomes [verbose] which allows the raw getblock output, with full info.
One use case is the bitcore-node server, which expects it from bitcoind.
This could be a breaking change for Peercoin. In that case,
the [verbose] param could be just added as a 3rd parameter.
> Change getblock rpc interface to be closer to recent bitcoind

- src/wallet.cpp
This pull request is reaction to issue #56, where I argued that thanks to rounding in the reward function, wallets sometimes create mints of zero value, which robs them of the coinage, but they gain nothing in return. This change causes that if the wallet generates mint with zero reward, it refuses to create it. There is no change in the protocol and the change is completely on the side of the wallet. 
It can still happen that the mint is zero or negative because of the fees for size. (Example - [block 69530](http://www.peercointalk.org/index.php?topic=2869.0).) But this is not to be prevented, since the mint transaction does work of joining the stakes without transaction fee, so unlike in the case of zero reward, there is benefit to the wallet in such case.
> Wallet refuses to create mints with zero reward. 

- src/init.cpp
- src/wallet.cpp
- src/wallet.h
- src/walletdb.cpp
- src/walletdb.h
This diagnostic tool removes all "tx" records from the wallet db,
then forces a full rescan, to rebuild "tx" records accurately.
Cherry-picked from:
518f3bdae3415fdb60cef984b69b36f2633c1fe1
Jeff Garzik <jgarzik@bitpay.com>
Fri Feb 14 11:33:07 2014 -0500
> Add -zapwallettxes cli/config option, used for wallet recovery

- src/rpcwallet.cpp
Prevents crashes like https://github.com/peercoin/peercoin/issues/215
> Limit unlock timeout to safe range

- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/locale/bitcoin_en.ts
hallo peercoin people! @peerchemist @backpacker69 @Sentinelrv 
This idea: https://github.com/peercoin/peercoin/issues/202
A couple of menu items in the Help menu that will open peercoin chat / forum :) I grabbed the "external_link" icon from wiki commons ( https://commons.wikimedia.org/wiki/File:External_link_icon.png ) as a stand-in ... although i kind of like the little globe :earth_africa:
> [issue#202] Helpful Help menu links to chat and forum.

- src/main.cpp
In the shunting area on line 2031, where blocks that do not have their previous block yet are handled, there is a special case for proof-of-stake blocks. That case can fail and a return false is called. Above that there is a creation of a CBlock by new. If the return false is reached, that CBlock\* that was allocated space is not handled. All I added was a delete pblock2; to handle memory better.
> Better memory management in ProcessBlock()

- src/qt/test/uritests.cpp
The Qt tests were introduced by the autotools backport.
This PR makes them work correctly.
> Fix Qt uriTests

- contrib/install_db4.sh
Instead of maintaining not-easily-tested instructions for building BerkeleyDB
in doc/build-unix.md, package the installation as a script in contrib/. This
allows shared usage from a number of contexts, e.g. Docker.
Thanks to @jonasschnelli, @laanwj for feedback.
Conflicts:
Makefile.am
doc/build-openbsd.md
doc/build-unix.md
Conflicted files were not included in the merge.
> [build] Add a script for installing db4

- src/rpcclient.cpp
- src/rpcserver.cpp
This fixes compilation against boost 1.66 and keeps compatibilty with older boost version through a single codebase.
briefly tested against 1.66, 1.64 and 1.55
> Fix compilation against boost 1.66

- bitcoin-qt.pro
This is a tiny patch to fix the Windows QT build using MXE on Linux for for v0.6.2ppc.rc4
Fix was to add -pthread to LIBS in win32 build in bitcoin-qt.pro
This is the error before my patch:
```
$ /usr/local/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 BOOST_LIB_SUFFIX=-mt BOOST_THREAD_LIB_SUFFIX=_win32-mt "QMAKE_CC=/usr/local/mxe/usr/bin/i686-w64-mingw32.static-gcc" "QMAKE_CXX=/usr/local/mxe/usr/bin/i686-w64-mingw32.static-g++" "OPENSSL_INCLUDE_PATH=/usr/local/mxe/usr/i686-w64-mingw32.static/include" "OPENSSL_LIB_PATH=/usr/local/mxe/usr/i686-w64-mingw32.static/lib" "BDB_INCLUDE_PATH=/usr/local/mxe/usr/i686-w64-mingw32.static/include" "BDB_LIB_PATH=/usr/local/mxe/usr/i686-w64-mingw32.static/lib" "MINIUPNPC_INCLUDE_PATH=/usr/local/mxe/usr/i686-w64-mingw32.static/include" …
```
> add -pthread to LIBS for MXE win32 build in bitcoin-qt.pro, fix for v0.6.2ppc.rc4

- src/qt/rpcconsole.cpp
Fix for time displayed on two separate lines in the RPC console
> Fix for time on two separate lines in RPC console

- src/qt/guiutil.cpp
When "Start Peercoin on system login" is selected, the created autostart entry should not be called "Bitcoin".
> Fix the name of the autostart entry (to develop)

- src/main.cpp
don't require complete resync when node has now invalid blocks in db
> don't shutdown when db contains now defunct blocks

- src/qt/forms/sendcoinsdialog.ui
- src/qt/forms/sendcoinsentry.ui
- src/qt/sendcoinsdialog.cpp
The changes in `sendcoinsentry.ui` came from Qt Designer, I changed the vertical sizing policy to "Fixed" so the send entries wouldn't try to expand vertically.
The changes in `sendcoinsdialog.cpp` are making the `VBoxLayout` `entries` put the entries at the top of the layout, otherwise it was putting it in the center of the page. I wanted to set the alignment in Qt Designer but it wasn't available for some reason :\
> A potential fix for the weird send entries layout.

- src/kernelrecord.cpp
- src/kernelrecord.h
- src/qt/mintingtablemodel.cpp
- src/wallet/rpcwallet.cpp
This resolves #543 so that the CoinDay column in the minting table works as intended.
This is based on `release-v0.10` instead of `develop`.
> Dynamically compute coin age

- .github/workflows/build.yml
opencode.net appears to be very dead, and probably outdated. Get it from github instead.
> Install appimagecraft from github

- .github/workflows/build.yml
Right now, whichever pipeline finishes last, will get to publish the latest development release.
This behavior is technically correct, but might not be very intuitive.
This commit will check if the commit we're building towards is included in the `latest` tag (published by the last pipeline which got to update the latest development release) and then disable the relevant release action.
> Old commits should not override new dev releases

- .github/workflows/build.yml
- contrib/devtools/symbol-check.py
- contrib/gitian-descriptors/assign_DISTNAME
- contrib/gitian-descriptors/gitian-osx.yml
This PR fixes the the macos builds for `release-0.12`, and bumps dependency workflows.
However windows
https://github.com/ihavenoface/peercoin/actions/runs/3385021959/jobs/5622685046#step:10:1775
```
STRIPPROG="/home/ubuntu/wrapped/x86_64-w64-mingw32-strip" /bin/bash /home/ubuntu/build/peercoin/distsrc-x86_64-w64-mingw32/build-aux/install-sh -c -s ./src/peercoin-util.exe ./release
/home/ubuntu/build/peercoin/distsrc-x86_64-w64-mingw32/build-aux/install-sh: ./src/peercoin-util.exe does not exist.
make: *** [Makefile:1265: /home/ubuntu/out/peercoin-5b474e26e536-win64-setup-unsigned.exe] Error 1
```
and linux
https://github.com/ihavenoface/peercoin/actions/runs/3385021959/jobs/5622684823#step:10:1263
```
Running symbol and dynamic library checks...
peercoind: symbol getrandom from …
```
> various build fixes

- contrib/gitian-descriptors/gitian-linux.yml
This commit forces `lpthread` which appears to be needed for ARM based builds.
Windows build continues to fail, due to issues with bit/peercoin-util.
> Fix ARM builds

- .github/workflows/build.yml
- src/Makefile.am
This PR updates the naming scheme of bitcoin-util, so that the pipeline can find the resulting executable.
Other pipeline changes are being tested.
> Rename bitcoin-util to peercoin-util

- .github/workflows/build.yml
- contrib/gitian-descriptors/gitian-linux.yml
- contrib/gitian-descriptors/gitian-osx.yml
- contrib/gitian-descriptors/gitian-win.yml
This PR updates a couple of things:  
First we drop building tests entirely. While we _should_ use them, we currently don't, so might as well disable them for some time savings.
Then, we get rid of the in-place genbuild update. Instead we just tell gitian to pull tags when needed. Much cleaner.
Further, we add `--with-gui` as a config flag, so that we can exit more reliably in case qt is acting up again.
We also allow `release-*` branches to push development builds to the release page, similar to what `develop` is doing now.
Lastly, replace `gzip` with `pigz`. Again for more time savings (single vs multi core archival).
> WIP: Various pipeline updates

- .github/workflows/build.yml
The release portion of https://github.com/peercoin/peercoin/pull/651 worked well in concept, but mixed up release hash and tag for some reason.  
This PR aims to clear that up.
> Minor fetch and release fixes

- .github/workflows/build.yml
Auto updates aren't supported currently, so let's drop the meta files.
> build: ignore appimage zsync files

- .github/workflows/build.yml
This PR will enable docker hub as a target. Multi arch is supported.  
Two things would be required first:
- Merge https://github.com/peercoin/packaging/pull/21 for a better base image
- Set up `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` in the repo secrets
> build: publish to dockerhub

- src/qt/intro.h
getPruneMiB() definition has been removed, so its declaration should be removed as well.
> Remove unused getPruneMiB() declaration

- src/clientversion.cpp
In "About Peercoin" window there is Bitcoin Github URL at moment. It shouldn't be so.
> Use correct Peercoin Github URL

- src/wallet/rpc/transactions.cpp
- src/wallet/spend.cpp
- src/wallet/transaction.h
Peercoin doesn't have RBF feature so these values aren't used anymore.
> Remove `replaces_txid` and `replaced_by_txid` keys

- src/validation.cpp
When loading UTXO snapshot, it seems logical to check if there is BLOCK_HAVE_DATA status.
I believe this check has been accidentally removed while removing pruning code.
> Do not process blocks without data during UTXO snapshot load

- src/qt/walletcontroller.cpp
This PR removes pruning reference in the dialog windows that appears on wallet close.
> Remove pruning residue in WalletController::closeWallet()

- src/interfaces/chain.h
- src/wallet/wallet.h
FeeCalculation struct is not used by Peercoin anymore. so its declarations should be removed.
> Remove unused FeeCalculation declarations

- test/functional/test_framework/messages.py
This PR fixes issues in `CBlockHeader`, `CBlock`  and `CTransaction` classes in test framework that prevented message capture parser from parsing network messages sent/received by Peercoin nodes.
Now it is possible to capture messages by using -messagecapture flag and parse the output with the help of `contrib/message-capture/message-capture-parser.py` Python script.
> Fix errors in message capture parser

- src/chainparams.cpp
Update nMinimumChainWork and defaultAssumeValid to block 500000 on testnet
> Update nMinimumChainWork and defaultAssumeValid (testnet)

- .github/workflows/build.yml
Docker base images / appimage for riscv64 aren't readily available anymore, so only the regular format needs to suffice.
> enable riscv64 builds

- src/chainparams.cpp
- src/kernel/chainparams.cpp
- src/kernel/chainparams.h
nPruneAfterHeight is not used anymore and has to be completely removed.
> Remove unused nPruneAfterHeight variable

- src/wallet/wallet.cpp
A unique `SignatureData` object should be created on each iteration of the loop; otherwise, it leads to incorrect signatures.
The bug has been described before on Discord.
> Construct a new SignatureData object  for each pcoin

- .github/workflows/build.yml
- contrib/guix/guix-build
- contrib/guix/libexec/build.sh
Caveat: I have not yet found a proper way to cache system packages from guix without exceeding the gh action cache size limit of 10GB, so builds will be slower for the time being.
> Replace gitian with guix in github actions

- .github/workflows/build.yml
- contrib/guix/Dockerfile
This pull request addresses the major painpoint in regards to guix, which is the time it takes to rebuild the system in case caches aren't reachable or have been evicted ahead of time.  
It does so by doing a two-round docker image, one for the common base system between architectures, and one for individual architectures. Each pipeline will still verify the image meta it pulls and rebuild if needed. Since the image is publicly available it should be possible to use it cross branch, which isn't the case with `actions/caches`.
> add guix prebuild

- src/wallet/wallet.cpp
@backpacker69 @peerchemist This change should apply the original log-distance optimisation when the `maxMintingUtxos` doesn't apply.
> Use log-distance optimisation when max utxos do not apply

- src/wallet/rpc/spend.cpp
This PR removes arguments that do not exist anymore from the help string for `sendtoaddress` RPC.
> rpc: Remove non-existing arguments from sendtoaddress help string

- src/qt/walletview.cpp
> don't request decryption for minting when wallet is not locked

- src/validation.cpp
> reject old block version once v15 activates

- .github/workflows/build.yml
Same effect as before, but now you can actually cancel the run if needed. Otherwise it might end up running indefinitely.
Should also fix a longstanding deprecation warning on release.
> make binary build cancelable and fix deprecation warning
